GameStore.WebUI/Models/GamesListViewModel.cs
using System.Collections.Generic;
using GameStore.Domain.Entities;

namespace GameStore.WebUI.Models
{
    public class GamesListViewModel
    {
        public IEnumerable<Game> Games { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

GameStore.WebUI/Models/PagingInfo.cs
using System;

namespace GameStore.WebUI.Models
{
    public class PagingInfo
    {
        // Кол-во товаров
        public int TotalItems { get; set; }

        // Кол-во товаров на одной странице
        public int ItemsPerPage { get; set; }

        // Номер текущей страницы
        public int CurrentPage { get; set; }

        // Общее кол-во страниц
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

GameStore.WebUI/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Domain.Abstract;
using GameStore.Domain.Entities;
using GameStore.WebUI.Models;

namespace GameStore.WebUI.Controllers
{
    public class GameController : Controller
    {
        private IGameRepository repository;
        public int pageSize = 4;

        public GameController(IGameRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1)
        {
            GamesListViewModel model = new GamesListViewModel
            {
                Games = repository.Games
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(game => game.GameId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = repository.Games.Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

GameStore.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameStore.WebUI.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult promka()
        {
            ViewBag.Message = "Это частичное представление.";
            return View();
        }
    }
}

GameStore.WebUI/Controllers/NavController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GameStore.Domain.Abstract;

namespace GameStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IGameRepository repository;

        public NavController(IGameRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Games
                .Select(game => game.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

GameStore.WebUI/Views/Game/List.cshtml
@using GameStore.WebUI.Models
@using GameStore.WebUI.HtmlHelpers
@model GamesListViewModel

@{
    ViewBag.Title = "Товары";
}



<div class="row">
    <div class="col-2">
        <ul class="nav flex-column">
            <li class="nav-item">
                @Html.Action("Menu", "Nav")
            </li>
        </ul>
    </div>

    <div class="col-8">
        @foreach (var p in @Model.Games)
        {
            @Html.Partial("GameSummary", p)//вывод списка товаров где p это количество товаров на одной странице
        }
    </div>
</div>

<p>
    <br>
</p>

<div style="padding-left:218px" class="row">
    <div class="col-8">
        <div class="btn btn-primary btn-lg active btn-info" role="button" aria-pressed="true">
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("List",
                new { page = x, category = Model.CurrentCategory }))
        </div>
    </div>
</div>

GameStore.WebUI/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home";
}
@using System.Web.Optimization


    <div class="carousel slide" data-ride="carousel" id="slides">
        <ul class="carousel-indicators">
            <li data-target="#slides" data-slide-to="0" class="active"></li>
            <li data-target="#slides" data-slide-to="1"></li>
            <li data-target="#slides" data-slide-to="2"></li>
        </ul>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Content/img/2.jpeg">
               
            </div>
            <div class="carousel-item ">
                <img src="~/Content/img/1.jpg">
            </div>
            <div class="carousel-item ">
                <img src="~/Content/img/civ3.jpg">
            </div>
        </div>
    </div>
        <!-- Основной блок сайта -->
        <div class="container-fluid">
            <div class="row jumbotron">
                <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 col-xl-10">
                    <p class="lead ">
                        Civilization — это серия пошаговых стратегий, основанная легендарным дизайнером Сидом Мейером,
                        главная задача которых — создать империю, способную выдержать испытание временем.
                        Вам предстоит исследовать новые земли, изучать технологии, побеждать других могущественных властителей и
                        строить величайшую в истории человечества цивилизацию.
                    </p>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-2">
                    <a href="#"> <button class="btn btn-success btn-lg" type="button">Читать дальше</button></a>
                </div>
            </div>
        </div>
        <!--Блок с характеристиками -->
        <div class="container-fluid">
            <div class="row text-center alert">
                <div class="col-12">
                    <h1 class="display-4">Основные районы</h1>
                </div>
                <hr>
                <div class="col12">
                    <p class="lead"></p>
                </div>
            </div>
        </div>
        <!-- Блок с описанием языков-->
        <div class="container-fluid padding">
            <div class="row text-center padding">
                <div class="col-xs-12 col-sm-6 col-md-4">

                    <a class="btn btn-dark btn-secondary btn-lg active" href='@Url.Action("promka", "Home")'>
                        <img src='@Url.Content("~/Content/img/icon1.png")' />
                    </a>

                        <h3>Промышленная зона</h3>
                        <p>Местонахождение промышленных сооружений и основной источник очков производства.</p>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <a class="btn btn-dark btn-secondary btn-lg active" href="#"><img src="~/Content/img/icon2.png" alt=""></a>
                    <h3>Театральная площадь</h3>
                    <p>Местонахождение культурных сооружений и основной источник очков культуры.</p>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <a class="btn btn-dark btn-secondary btn-lg active" href="#"><img src="~/Content/img/icon3.png" alt=""></a>
                    <h3>Кампус</h3>
                    <p>Местонахождение научных сооружений и основной источник очков науки.</p>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <a class="btn btn-dark btn-secondary btn-lg active" href="#"><img src="~/Content/img/icon4.png" alt=""></a>
                    <h3>Священное место</h3>
                    <p>Местонахождение религиозных сооружений и основной источник очков веры.</p>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <a class="btn btn-dark btn-secondary btn-lg active" href="#"><img src="~/Content/img/icon5.png" alt=""></a>
                    <h3>Военный лагерь</h3>
                    <p>Отвечает за производство юнитов и оборону городов.</p>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <a class="btn btn-dark btn-secondary btn-lg active" href="#"><img src="~/Content/img/icon6.png" alt=""></a>
                    <h3>Гавань</h3>
                    <p>Отвечает за морские коммуникации, является одним из основных источников золота.</p>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <a class="btn btn-dark btn-secondary btn-lg active" href="#"><img src="~/Content/img/icon7.png" alt=""></a>
                    <h3>Центр города</h3>
                    <p>Основной райно, появляестя после активирования поселенца, является одним из древних районов города</p>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <a class="btn btn-dark btn-secondary btn-lg active" href="#"><img src="~/Content/img/icon8.png" alt=""></a>
                    <h3>Центр коммерции</h3>
                    <p>Местонахождение финансовых и торговых сооружений, основной источник золота</p>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <a class="btn btn-dark btn-secondary btn-lg active" href="#"><img src="~/Content/img/icon9.png" alt=""></a>
                    <h3>Космопорт </h3>
                    <p>Район необходимый для совершения научной победы</p>
                </div>
            </div>
            <hr class="my-4">
        </div>
        <!-- секция с изображениями <div class="container-fluid padding">
        <div class="row padding" >
            <dic class="col-lg-6">
                <h2 >Xljjkljkl</h2>
                <p>Lorem ipsum dolor sit amet, consectetur
                adipisicing elit. Ullam, voluptatibus quibusdam
                sint? Dolore, minus, voluptas nihil ea quam eveniet
                deleniti.
                <br><br>
                Lorem ipsum dolor sit amet, consectetur
                adipisicing elit. Ullam, voluptatibus quibusdam
                sint? Dolore, minus, voluptas nihil ea quam eveniet
                deleniti
                <br><br>
                Lorem ipsum dolor sit amet, consectetur
                adipisicing elit. Ullam, voluptatibus quibusdam
                sint? Dolore, minus, voluptas nihil ea quam eveniet
                deleniti.</p>
                <br>
                <a href="#" class="btn btn-danger">	Xbnf</a>

            </dic>
            <dic class="offse-lg-2 col-lg-4">
                <br>
                <img src="" class="img-fluid" alt="">
            </dic>
        </div>
    </div>-->
        <div class="container-fluid padding">
            <div class="row alert text-center">
                <div class="col-12">
                    <h1 class="display-4">Другие игры на данную тематику</h1>
                    <hr>
                </div>
            </div>
        </div>
        <!-- Другие игры -->
        <div class="container padding">
            <div class="row padding">
                <div class="col-md-4">
                    <div class="card">
                        <img src="~/Content/img/dopolnenie1.png" class="card-img-top" alt="">
                        <div class="card-body">
                            <h4 class="card-title">HUMANKNG</h4>
                            <p class="card-text">
                                Грядущая компьютерная игра в жанре
                                глобальной пошаговой 4X-стратегии ближайший конкурент Civilization.
                                Выпуск игры запланирован на 2020 год для Microsoft Windows
                            </p>
                            <a href="#" class="btn btn-warning">Посмотреть</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <img src="~/Content/img/dopolnenie2.jpg" class="card-img-top" alt="">
                        <div class="card-body">
                            <h4 class="card-title">Sid Meier’s Civilization: Beyond Earth</h4>
                            <p class="card-text">
                                История игры происходит примерно через 600 лет от настоящего, когда люди должны покинуть
                                Землю в результате события под названием «Великая ошибка».
                                В игре человечество путешествует по космосу, чтобы начать новую жизнь,
                                колонизируя внеземные планеты
                            </p>
                            <a href="#" class="btn btn-warning">Посмотреть</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <img src="~/Content/img/dopolnenie3.jpg" class="card-img-top" alt="">
                        <div class="card-body">
                            <h4 class="card-title">Endless Legend</h4>
                            <p class="card-text">
                                Глобальная фэнтези-стратегия. Цель игры -
                                подчинить мир Аурига одной из одиннадцати основных фракций путем дипломатии или войны,
                                одновременно открывая новые технологии, исследуя мир и основывая города.
                            </p>
                            <a href="#" class="btn btn-warning">Посмотреть</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

GameStore.WebUI/Views/Home/promka.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home"; }
@using System.Web.Optimization

<!DOCTYPE html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<div class="m-4">
    <link rel="stylesheet" href="promka.css">
    <h1>Промышленная зона </h1>
    <p>
        Промышленная зона позволяет увеличить производство города или городов.<br>
        Ганза - уникальный район Германии, который отличается бонусами за соседство.
    </p>
</div>

<div class="m-4">
    <table border="1">
        <tr>
            <th>Название</th>
            <th>Требования</th>
            <th  width ="40px" align="center"> <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt="" class="center-img"></th>
            <th align="center"> <img src="~/Content/img/Комерческий_район_(Civ6).png" alt="" class="center-img"></th>
            <th>Доход</th>
            <th>Доход от соседств</th>
            <th>Специалист</th>
        </tr>
        <tr>
            <td> <b>Промышленная зона </b></td>
            <td align="center">
                Ученичество <br>
                <img src="~/Content/img/Apprenticeship.png" alt="" class="center-img">
            </td>
            <td width="40px" align="center"> 54</td>
            <td width="30px" align="center"> 1</td>
            <td>+1 очко Великого Инженера</td>
            <td>
                +2 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> производство рядом с акведуком, баней, каналом и дамбой   	<br>
                +1 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> производство рядом с каменоломней   	<br>
                +1 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> производство рядом со стратегическим ресурсом   	<br>
                +0.5 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> производство рядом с каждым рудником, лесопилкой   	<br>
                +0.5 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> производство рядом с другим районом   	<br>
            </td>
            <td>+2 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""></td>
        </tr>
        <tr>
            <td><b>Ганза</b></td>
            <td align="center">
                Ученичество. Германия. Заменяет Промышленную зону.<br>
                <img src="~/Content/img/Apprenticeship.png" alt="" class="center-img">
            </td>
            <td width ="40px" align="center">27</td>
            <td width ="30px" align="center">1</td>
            <td>+1 очко Великого Инженера</td>
            <td>
                +2 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> производство рядом с центром коммерции, акведуком, каналом и дамбой  	<br>
                +1 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> производство рядом с ресурсом 	<br>
                +0.5 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt="">производство рядом с другим районом   	<br>
            </td>
            <td>+2 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""></td>
        </tr>

    </table>
</div>

<div class="m-4">
    <p>
        Здания в районе дают производство, но первое здание мастерская даёт производство только городу,<br> а остальные здания действуют на города в некотором радиусе от промышленного района.
    </p>
</div>


<div class="m-4">
    <table border="1">
        <tr>
            <th>Название</th>
            <th>Требования</th>
            <th width ="40px" align="center">	<img src="~/Content/img/Промышленная_зона_(Civ6).png" alt="" class="center-img"></th>
            <th width ="30px" align="center">	<img src="~/Content/img/Комерческий_район_(Civ6).png" alt="" class="center-img"></th>
            <th>Доход</th>
        </tr>
        <tr>
            <td align="center">
                <b>Мастерская</b> <br>
                <img src="~/Content/img/Workshop.png" alt="" class="center-img">
            </td>
            <td align="center">
                Ученичество. Германия. Заменяет Промышленную зону.<br>
                <img src="~/Content/img/Apprenticeship.png" alt="" class="center-img">
            </td>
            <td width="40px" align="center">195</td>
            <td width="30px" align="center">1</td>
            <td>
                +2 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> <br>
                +1 специалист	<br>
                +1 очко Великого Инженера<br>
            </td>
        </tr>
        <tr>
            <td align="center">
                <b>Фабрика</b> <br>
                <img src="~/Content/img/Factory.png" alt="" class="center-img">
            </td>
            <td align="center">
                Индустриализация <br>
                <img src="~/Content/img/Industrialization.png" alt="" class="center-img">
            </td>
            <td width ="40px" align="center">390</td>
            <td width ="30px" align="center">2</td>
            <td>
                +3 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> 	<br>
                +3 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> когда электрифицирована (2 энергии)
                +1 специалист	<br>
                +1 очко Великого Инженера<br>
                Производство даётся всем городам в радиусе 6 тайлов.<br>
            </td>
        </tr>
        <tr>
            <td align="center">
                <b>Фабрика электроники</b><br>
                <img src="~/Content/img/Factory.png" alt="" class="center-img">
            </td>
            <td align="center">
                Япония. Индустриализация. Заменяет Фабрику <br>
                <img src="~/Content/img/Industrialization.png" alt="" class="center-img">
            </td>
            <td width="40px" align="center">390</td>
            <td width="30px" align="center">2</td>
            <td>
                +3 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> 	<br>
                +5 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> когда электрифицирована (2 энергии)
                +1 специалист	<br>
                +1 очко Великого Инженера<br>
                +4 <img src="Культура.png" alt=""> <br>
                Производство даётся всем городам в радиусе 6 тайлов.<br>
            </td>
        </tr>
    </table>
</div>
<div class="m-4">
    <p>Здания электрификации можно построить после строительства фабрики.</p>

    <table border="1">
        <tr>
            <th>Название</th>
            <th>Требования</th>
            <th width ="40px" align="center">	<img src="~/Content/img/Промышленная_зона_(Civ6).png" alt="" class="center-img"></th>
            <th width ="30px" align="center">	<img src="~/Content/img/Комерческий_район_(Civ6).png" alt="" class="center-img"></th>
            <th>Доход</th>
        </tr>
        <tr>
            <td align="center">
                Угольная электростанция <br>
                <img src="~/Content/img/Coal_Power_Plant.png" alt="" class="center-img">
            </td>
            <td align="center">
                Индустриализация. Нельзя построить вместе с мазутной и ядерной электростанциями <br>
                <img src="~/Content/img/Industrialization.png" alt="" class="center-img">
            </td>
            <td width ="40px" align="center">300</td>
            <td width ="30px" align="center">3</td>
            <td>
                Бонусное <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> равное <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> бонусу за соседство<br>
                +1 специалист<br>
                +1 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> специалистам<br>
                +1 очко Великого Инженера<br>
                Производственный бонус распространяется на центры городов в радиусе 6 тайлов<br>
                Производственный бонус из разных электростанций не суммируется.<br>
                Автоматические конвертирует уголь в электроэнергию городам в радиусе 6 тайлов.<br>
                1 уголь даёт 4 энергии<br>
                Выделяет большое количество CO2<br>
            </td>
        </tr>
        <tr>
            <td align="center">
                Мазутная электростанция <br>
                <img src="~/Content/img/Oil_Power_Plant.png" alt="" class="center-img">
            </td>
            <td align="center">
                Электричество. Нельзя построить вместе с угольной и ядерной электростанциями<br>
                <img src="~/Content/img/Electricity.png" alt="" class="center-img">
            </td>
            <td width ="40px" align="center">360</td>
            <td width ="30px" align="center">3</td>
            <td>
                +3 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""><br>
                +1 специалист<br>
                +1 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> специалистам<br>
                +1 очко Великого Инженера<br>
                Производственный бонус распространяется на центры городов в радиусе 6 тайлов<br>
                Производственный бонус из разных электростанций не суммируется.<br>
                Автоматические конвертирует нефть в электроэнергию городам в радиусе 6 тайлов.<br>
                1 нефть даёт 4 энергии<br>
                Выделяет большое количество CO2<br>
            </td>
        </tr>

        <tr>
            <td align="center">
                Ядерная электростанция <br>
                <img src="~/Content/img/Nuclear_Power_Plant.png" alt="" class="center-img">
            </td>
            <td align="center">
                Расщепление ядра. Нельзя построить вместе с угольной и мазутной электростанциями<br>
                <img src="~/Content/img/Nuclear_Fission.png" alt="" class="center-img">
            </td>
            <td width="40px" align="center">480</td>
            <td width="30px" align="center">3</td>
            <td>
                +4 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""><br>
                +3 <img src="~/Content/img/наука.png" alt=""><br>
                +1 специалист<br>
                +1 <img src="~/Content/img/Промышленная_зона_(Civ6).png" alt=""> специалистам<br>
                +1 очко Великого Инженера<br>
                Производственный бонус распространяется на центры городов в радиусе 6 тайлов<br>
                Производственный бонус из разных электростанций не суммируется.<br>
                Автоматические конвертирует уран в электроэнергию городам в радиусе 6 тайлов.<br>
                1 нефть даёт 16 энергии<br>
                Выделяет большое количество CO2<br>
                Выделяет очень маленькое количество CO2<br>
                Есть вероятность взрыва ядерного реактора<br>
            </td>
        </tr>
    </table>
</div>

GameStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

<div style="padding:20px">

    @Html.ActionLink("Все категории", "List", "Game", null,
        new { @class = "btn btn-block btn-default btn-lg btn-outline-dark" })
    <p>

    </p>

    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new
        {
            controller = "Game",
            action = "List",
            category = link,
            page = 1
        }, new
        {
            @class = "btn btn-block btn-default btn-lg btn-outline-primary"
                + (link == ViewBag.SelectedCategory ? "btn btn-outline-primary" : "")
        })
    }
</div>

GameStore.WebUI/Views/Shared/GameSummary.cshtml
@model GameStore.Domain.Entities.Game



    <div class="well">
        <h3>
            <strong>@Model.Name</strong>
            <span class="pull-right label label-primary">@Model.Price.ToString("# лей")</span>
        </h3>
        <span class="lead">@Model.Description</span>
    </div>

GameStore.WebUI/Views/Shared/_Footer.cshtml
<br>
<hr class="my-2">
<footer class="page-footer font-small mdb-color lighten-3 pt-4">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">

                <!-- Content -->
                <h5 class="font-weight-bold text-uppercase mb-4">Footer Content</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur, eligendi!</p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos excepturi itaque ratione
                    consequatur quis veritatis!
                </p>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 mx-auto my-md-4 my-0 mt-4 mb-1">

                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mb-4">About</h5>

                <ul class="list-unstyled">
                    <li>
                        <p>
                            <a href="#!">ГЛАВНВЯ</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="#!">О НАС</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="#!">СЕРВИС</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="#!">КОМАНДА</a>
                        </p>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">

                <!-- Contact details -->
                <h5 class="font-weight-bold text-uppercase mb-4">Address</h5>

                <ul class="list-unstyled">
                    <li>
                        <p>
                            <i class="fas fa-home mr-3"></i> Республика Молдова, Кишинёв
                        </p>
                    </li>
                    <li>
                        <p>
                            <i class="fas fa-envelope mr-3"></i> info@example.com
                        </p>
                    </li>
                    <li>
                        <p>
                            <i class="fas fa-phone mr-3"></i> + 01 234 567 88
                        </p>
                    </li>
                    <li>
                        <p>
                            <i class="fas fa-print mr-3"></i> + 01 234 567 89
                        </p>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">
        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->
</footer>
<!-- Footer -->

GameStore.WebUI/Views/Shared/_Header.cshtml
<nav class="navbar-expand-md navbar navbar navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
        <a href="#" class="navbar-brad"><img src="~/Content/img/4.png" alt=""></a>
        <a href="#" class="navbar-brad"><img src="~/Content/img/icon1.png" alt=""></a>
        <a href="#" class="navbar-brad"><img src="~/Content/img/icon2.png" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Главная", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Про нас</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Контакты</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Сервис</a>
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Магазин", "List", "Game",null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Регистрация</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

GameStore.WebUI/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>eUse System | @ViewBag.Title</title>

    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/Global/css")
    @Styles.Render("~/bundles/Slaider/css")
    @Styles.Render("~/bundles/Block/css")

    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/popper.min/js")

</head>
<body>

    @Html.Partial("_Header")

    @RenderBody()

    @Html.Partial("_Footer")


</body>
</html>